---
title: Laurent Chotard
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
    navigation: false
    ordre: 9
    permalink: 
url: 
baseurl: 
google-tracking-id: 
force-https: false
lang: fr
author: Laurent Chotard
description: Mon métier est l'accompagnement de l'individu dans son environnement
  - cohésion, individu, efficacité, management, comportemental
keywords: cohesion, individu, efficacité, management, comportemental
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/bg-ponton.jpg"
dynamic-typing: false
shuffle: true
loop: true
loop-count: false
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
- text: The lower you fall, the higher you'll fly.
- text: Where’s your will to be weird?
me-img: "/img/logo-cccohesion.jpg"
color-browser: "#000000"
apple-status-bar-style: black
web-app-mode: true
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
enable-gesture-navigation: true
post-preview-words: 96
email-share: false
fb-share: true
twitter-share: false
linkedin-share: true
reddit-share: false
google-plus-share: false
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false
disqus-shortname: 
syntax-highlight: true
timeline-img: "/img/timeline/default.png"
email: chotardconseil@cccohesion.com
author_blurb: La performance du groupe n’existe que s’il y a confiance et sens partagé.
author_blurb_image: "/img/author.png"
social:
- title: facebook
  url: http://www.facebook.com/cccohesion
- title: linkedin
  url: https://fr.linkedin.com/in/laurent-chotard-b380405b
assets:
  compress:
    css: true
    js: true
  autoprefixer:
    browsers:
    - last 2 versions
    - IE > 9
pages_list:
  About: about
  Blog: latest-post
  Timeline: timeline
  Contact: contact
exclude:
- LICENSE
- README.md
- CONTRIBUTING
- CONTRIBUTORS
- scripts
sass:
  style: compressed
gems:
- jekyll-assets
- jekyll-offline
